### ISSUE TITLE
Doesn't Seem to Render on My Install - just spits out the link as text

### ISSUE THREAD

**Issue by iChris** [gfscott/eleventy-plugin-youtube-embed#21]
I only know enough to be dangerous here so I'm sorry if I don't pass along enough info to help out.

Blog post code:

<img src="https://d.pr/i/snV7Qz+">

Blog post output:

<img src="https://d.pr/i/XxkNvj+">

Eleventy.js code:

<img src="https://d.pr/i/L8ywtT+">

Node Modules directory:

<img src="https://d.pr/i/OvleD1+">

If there's anything else you'd need to see to help figure out the issue, I'm happy to send it over! (and no panic / rush. Just a personal blog. Thanks for the plugin!)

**Comment by iChris** [comment]
Adding package.json screenshot to show version number of plugin at 1.3.2:

<img src="https://d.pr/i/zUvGtW+">

**Comment by gfscott** [comment]
Hey @iChris — thanks for filing an issue, hope I can help!

I think the problem might be in your Eleventy.js config file:

```js
config.addPlugin(rssPlugin);
config.addPlugin(syntaxHighlight);

const embedYouTube = require("eleventy-plugin-youtube-embed");

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(embedYouTube);
};
```
If the RSS and Syntax Highlighting plugins are working, then you should be able to just drop the whole `module.exports` block and try this:

```js
// However you `require` the rss and syntax plugins, just follow the same pattern!
const embedYouTube = require("eleventy-plugin-youtube-embed");

config.addPlugin(rssPlugin);
config.addPlugin(syntaxHighlight);
config.addPlugin(embedYouTube);
```

Let me know if that doesn't work!

I realize now looking at your config file that the readme doesn't do a great job of contextualizing the installation. I'll try to clarify things in the next update!

**Comment by iChris** [comment]
That worked great! Thanks! 

Screenshot of updated eleventy.js <img src="https://d.pr/i/JXJcS2+">
