### ISSUE TITLE
Support The Paul Irish Lite YouTube Embed™

### ISSUE THREAD

**Issue by zachleat** [gfscott/eleventy-plugin-youtube-embed#26]
https://github.com/paulirish/lite-youtube-embed

**Comment by gfscott** [comment]
I'm into this — looked into it with #4 and decided against at the time, for reasons that escape me now.

How I see it working (just jotting this down for future reference):

```js
eleventyConfig.addPlugin(embedYouTube, {
  lite: true
});
```

Which would trigger alternate lite-youtube embed code output from [lib/buildEmbed.js](https://github.com/gfscott/eleventy-plugin-youtube-embed/blob/main/lib/buildEmbed.js). For ease of use default to load the external CSS and JS [from jsdelivr](https://cdn.jsdelivr.net/gh/paulirish/lite-youtube-embed@master/src/), with the option to specify your own URL. Maybe optional inlining?
