### ISSUE TITLE
Add an option to inline the Lite YouTube Embed css & js

### ISSUE THREAD

**Issue by GrimLink** [gfscott/eleventy-plugin-youtube-embed#49]
The css and Js for the Lite YouTube Embed are both small enough to inline it.
This removes the css from from being render blocking.

**Comment by gfscott** [comment]
Hey @GrimLink — Really sorry for taking so long to reply here!

I did dig into some approaches here, and while inlining the CSS is fairly trivial, I haven't been able to think of a good way to inline the JS that feels solid and secure.

So two questions!

a) would you be OK having just the inline CSS feature on its own to start?
b) anyone have any ideas on how to safely inline JavaScript inside HTML strings using Node?

**Comment by GrimLink** [comment]
Hi @gfscott 
No problem, for the late reply 😉

> a) would you be OK having just the inline CSS feature on its own to start?

Yes, totally.

> b) anyone have any ideas on how to safely inline JavaScript inside HTML strings using Node?

Not sure, not an expert at node 😅

Another option would be to have the option to disable the JS en CSS injection.
Allow the author do it them selfs.

I use the 11ty frontmatter to add specific styles for a page, as an example.
