### ISSUE TITLE
Error deploying : lite-yt-embed.css missing

### ISSUE THREAD

**Issue by neo7-studio-web** [gfscott/eleventy-plugin-youtube-embed#52]
Error: ENOENT: no such file or directory, open '/vercel/path2/node_modules/eleventy-plugin-youtube-embed/node_modules/lite-youtube-embed/src/lite-yt-embed.css'

Deploying from Vercel with both 1.5 and 1.6.1

**Comment by Antonio-Laguna** [comment]
Seeing the same here.

**Comment by gfscott** [comment]
@neo7-studio-web Thanks so much for reporting this!

I was able to reproduce the issue and validate @Antonio-Laguna’s fix in #53 —  just published [1.6.2.](https://github.com/gfscott/eleventy-plugin-youtube-embed/releases/tag/v1.6.2).

**Comment by neo7-studio-web** [comment]
Well done, thank you for your  great responsiveness. I confirm it works now on 1.6.2.
